#! /bin/bash

# See
#
# https://gricad-gitlab.univ-grenoble-alpes.fr/schreibm/ci-test-gricad/-/settings/ci_cd#js-pipeline-triggers
#

curl -X POST \
	--no-progress-meter \
	--fail \
	-F token=glptt-1ca042bc9cbe280aa92aa59f0b6dc3463a4b04b0 \
	-F ref=main \
	https://gricad-gitlab.univ-grenoble-alpes.fr/api/v4/projects/16301/trigger/pipeline > /dev/null


if [[ $? -eq 0 ]]; then
	echo "CI pipeline triggered successfully"
else
	echo "ERROR"
	echo "ERROR: Failed to trigger CI pipeline!"
	echo "ERROR"
fi
