#! /bin/bash

echo "Hello! This is a .git/hooks/pre-commit hook"

echo "Updating Gitlab CI files"
./mule_local/bin/mule.ci_gitlab.setup_ci_tests.py || exit 1

echo "Adding potential travis updates"
git add ./.gitlab-ci.yml || exit 1

exit 0
