#! /usr/bin/env python3

import sys

# Load simulation time to get reference file
import imp
jc = imp.load_source('benchmark_create_job_scripts', './benchmark_create_job_scripts')
print(jc.p.runtime.simtime)


import glob
directories = glob.glob("job_*")
directories.sort()

errors = []

for d in directories:

	fname = d+'/output.out'

	with open(fname) as f:
		content = f.readlines()

	error = -1
	for l in content:
		s = l.split("\t")

		if s[0] != "[ERRORS]":
			continue

		simtime = s[1]

		if abs(float(simtime.replace('simtime=', '')) - jc.p.runtime.simtime) > 1e-10:
			continue

		error = float(s[2].replace('error_l1_phi=', ''))

	if error == -1:
		print("[ERROR] Directory: "+d)
		print("[ERROR] No error at simtime="+str(jc.p.runtime.simtime)+" found")
		sys.exit(1)


	g = 9.80616
	gh = 29400
	rel_error_h = error / gh

	print(d+": rel_error_h = "+str(rel_error_h))
	errors.append(rel_error_h)


import math
import numpy

max_error = numpy.amax(numpy.abs(errors))
print("max_error: "+str(max_error))

err_threshold = 1e-10
if max_error > err_threshold or not math.isfinite(max_error):
	raise Exception("Relative overall error exceeeds threshold "+str(err_threshold))

