#! /usr/bin/env python3

import glob
import subprocess
import os
import sys
import imp
from subprocess import Popen, PIPE

# Load simulation time to get reference file
jc = imp.load_source('jobs_create_scripts', './jobs_create_scripts')


directories = glob.glob("script_*")
directories.sort()

max_error = -1

for d in directories:

	fname = d+'/output.out'

	with open(fname) as f:
		content = f.readlines()

	error = -1
	for l in content:
		s = l.split("\t")

		if s[0] != "[ERRORS]":
			continue

		simtime = s[1]

		if abs(float(simtime.replace('simtime=', '')) - jc.p.runtime.simtime) > 1e-10:
			continue

		error = float(s[2].replace('error_l1_phi=', ''))

	if error == -1:
		print("[ERROR] Directory: "+d)
		print("[ERROR] No error at simtime="+str(jc.p.runtime.simtime)+" found")
		sys.exit(1)


	g = 9.80616
	gh = 29400
	rel_error_h = error / gh

	print(d+": rel_error_h = "+str(rel_error_h))

	max_error = max(max_error, rel_error_h)


err_threshold = 1e-10
if max_error > err_threshold:
	raise Exception("Relative overall error exceeeds threshold "+str(err_threshold))
